
# dataset info
dataset_name: "UFO-120" 
dataset_path: "/home/xie/xcl/paper/data/UFOtranval/train_val/"
checkpoint_dir: "checkpoints测试/"   # 模型保存路径
# image info
chans: 3
im_width: 256  #320
im_height: 256 #240

# other params
val_interval: 1000 # steps
ckpt_interval: 20  # epochs



 
